### ISSUE TITLE
Support not removed

### ISSUE THREAD

**Issue by goldjunge91** [5axes/CustomSupportEraserPlus#2]
hi
i tried today the simple support eraser and its not working i have to print my stuff so i'm going on and slice it with support and check it later.
Now is later :-) for me
and i install your plugin 
test with support Eraser
i added my files as cura project
![Screenshot 2023-03-23 165026](https://user-images.githubusercontent.com/30201929/227369674-b4dd1e95-84c2-4d43-bba7-a4b275a58b6f.png)

Test with CustomSupportEraserPlus
but as we can see on my picture the copy of the first Erase cube works the other one not.
![Screenshot 2023-03-23 223936](https://user-images.githubusercontent.com/30201929/227370306-154bbc7d-707b-4385-99ad-519e89761cf3.png)

[support not removed.zip](https://github.com/5axes/CustomSupportEraserPlus/files/11056523/support.not.removed.zip)

**Comment by 5axes** [comment]
Because it's not a support but a part of the brim. The support eraser can't do anything to remove this toolpath. Looks like a bug already seen in other bug report.

**Comment by goldjunge91** [comment]
ooh you are soo right. i have active only outside but some of the creepy latters get brim hahahaha i total forgot the brim. thanks for you fast answer!!!
